// src/lib/components/Autocomplete.svelte
<script lang="ts">
  import { onMount } from "svelte";

  type Props = {
    items: { label: string; value: string; detail?: string }[];
    value: string;
    placeholder?: string;
    id?: string;
    onselect?: (value: string) => void;
  };

  let { items, value = $bindable(), placeholder = "", id, onselect }: Props = $props();

  let query = $state("");
  let open = $state(false);
  let highlightIdx = $state(0);
  let inputEl = $state<HTMLInputElement | null>(null);
  let listEl = $state<HTMLDivElement | null>(null);

  // Sync query from selected value's label
  $effect(() => {
    const match = items.find((i) => i.value === value);
    query = match ? match.label : value;
  });

  const filtered = $derived.by(() => {
    if (!query.trim()) return items;
    const q = query.toLowerCase();
    return items.filter(
      (i) =>
        i.label.toLowerCase().includes(q) ||
        i.value.toLowerCase().includes(q) ||
        (i.detail?.toLowerCase().includes(q) ?? false),
    );
  });

  function select(item: { label: string; value: string }) {
    value = item.value;
    query = item.label;
    open = false;
    onselect?.(item.value);
  }

  function handleInput() {
    open = true;
    highlightIdx = 0;
  }

  function handleFocus() {
    open = true;
    highlightIdx = 0;
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      highlightIdx = Math.min(highlightIdx + 1, filtered.length - 1);
      scrollHighlightIntoView();
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      highlightIdx = Math.max(highlightIdx - 1, 0);
      scrollHighlightIntoView();
    } else if (e.key === "Enter") {
      e.preventDefault();
      if (open && filtered[highlightIdx]) {
        select(filtered[highlightIdx]);
      }
    } else if (e.key === "Escape") {
      open = false;
    }
  }

  function scrollHighlightIntoView() {
    requestAnimationFrame(() => {
      listEl?.children[highlightIdx]?.scrollIntoView({ block: "nearest" });
    });
  }

  function handleClickOutside(e: MouseEvent) {
    if (inputEl && !inputEl.closest(".sg-autocomplete")?.contains(e.target as Node)) {
      open = false;
    }
  }

  onMount(() => {
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  });
</script>

<div class="sg-autocomplete relative">
  <input
    bind:this={inputEl}
    bind:value={query}
    oninput={handleInput}
    onfocus={handleFocus}
    onkeydown={handleKeydown}
    {id}
    {placeholder}
    class="w-full rounded border border-[var(--sg-input-border)] bg-[var(--sg-input-bg)] px-2 py-1 text-xs text-[var(--sg-text)] placeholder-[var(--sg-text-faint)] outline-none focus:border-[var(--sg-input-focus)]"
    role="combobox"
    aria-expanded={open}
    aria-controls="sg-autocomplete-list"
    aria-autocomplete="list"
    autocomplete="off"
    spellcheck="false"
    autocorrect="off"
    autocapitalize="off"
  />

  {#if open && filtered.length > 0}
    <div
      bind:this={listEl}
      id="sg-autocomplete-list"
      class="absolute left-0 right-0 top-full z-40 mt-1 max-h-48 overflow-auto rounded border border-[var(--sg-border)] bg-[var(--sg-surface)] shadow-lg"
      style="animation: sg-slide-up 0.12s ease-out"
      role="listbox"
    >
      {#each filtered as item, i}
        <button
          class="flex w-full cursor-pointer items-center gap-2 px-2 py-1.5 text-left text-xs {i === highlightIdx ? 'bg-[var(--sg-surface-raised)] text-[var(--sg-text)]' : 'text-[var(--sg-text-dim)]'}"
          onmouseenter={() => (highlightIdx = i)}
          onclick={() => select(item)}
          role="option"
          aria-selected={i === highlightIdx}
        >
          <span class="min-w-0 flex-1 truncate">{item.label}</span>
          {#if item.detail}
            <span class="shrink-0 text-[10px] text-[var(--sg-text-faint)]">{item.detail}</span>
          {/if}
        </button>
      {/each}
    </div>
  {/if}
</div>

// packages/ui/src/components/Autocomplete.tsx
import {
  useState,
  useRef,
  useEffect,
  type KeyboardEvent,
  type ReactNode,
} from 'react';
import { ChevronDown } from 'lucide-react';

export type AutocompleteOption<T = string> = {
  value: T;
  label: string;
  description?: string;
};

type Props<T> = {
  options: AutocompleteOption<T>[];
  value?: T;
  onChange: (value: T) => void;
  placeholder?: string;
  /** Custom render for each option row. */
  renderOption?: (opt: AutocompleteOption<T>, active: boolean) => ReactNode;
  className?: string;
  disabled?: boolean;
  id?: string;
};

/**
 * Keyboard-navigable autocomplete/combobox. Matches old Svelte Autocomplete
 * behaviour: type to filter, arrow keys to navigate, Enter/click to select.
 */
export function Autocomplete<T = string>({
  options,
  value,
  onChange,
  placeholder = 'Select…',
  renderOption,
  className,
  disabled,
  id,
}: Props<T>) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [activeIdx, setActiveIdx] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);
  const listRef = useRef<HTMLUListElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const filtered = options.filter(o =>
    !query.trim() || o.label.toLowerCase().includes(query.toLowerCase())
  );

  const selectedLabel = options.find(o => o.value === value)?.label ?? '';

  // Close when clicking outside.
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        setOpen(false);
        setQuery('');
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  // Scroll active item into view.
  useEffect(() => {
    const el = listRef.current?.children[activeIdx] as HTMLElement | undefined;
    el?.scrollIntoView({ block: 'nearest' });
  }, [activeIdx]);

  function select(opt: AutocompleteOption<T>) {
    onChange(opt.value);
    setOpen(false);
    setQuery('');
  }

  function handleKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setActiveIdx(i => Math.min(i + 1, filtered.length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setActiveIdx(i => Math.max(i - 1, 0));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const opt = filtered[activeIdx];
      if (opt) select(opt);
    } else if (e.key === 'Escape') {
      setOpen(false);
      setQuery('');
    }
  }

  function handleOpen() {
    if (disabled) return;
    setOpen(true);
    setActiveIdx(0);
    requestAnimationFrame(() => inputRef.current?.focus());
  }

  const inputCls = 'w-full px-[10px] py-[6px] bg-(--sg-input-bg) border border-(--sg-input-border) rounded-[6px] text-xs text-(--sg-text) outline-none focus:border-(--sg-input-focus)';
  const triggerCls = 'w-full flex items-center justify-between gap-2 px-[10px] py-[6px] bg-(--sg-input-bg) border border-(--sg-input-border) rounded-[6px] text-xs text-(--sg-text) cursor-pointer hover:border-(--sg-input-focus) disabled:opacity-50 disabled:cursor-not-allowed';

  return (
    <div ref={containerRef} className={['relative w-full', className].filter(Boolean).join(' ')}>
      {open ? (
        <input
          ref={inputRef}
          id={id}
          className={inputCls}
          value={query}
          onChange={e => { setQuery(e.target.value); setActiveIdx(0); }}
          onKeyDown={handleKeyDown}
          placeholder={selectedLabel || placeholder}
          aria-autocomplete="list"
          aria-expanded
          aria-controls="sg-autocomplete-list"
          role="combobox"
        />
      ) : (
        <button
          id={id}
          className={triggerCls}
          onClick={handleOpen}
          disabled={disabled}
          type="button"
        >
          <span className="truncate">{selectedLabel || <span className="text-(--sg-text-faint)">{placeholder}</span>}</span>
          <ChevronDown size={12} className="shrink-0 text-(--sg-text-faint)" />
        </button>
      )}

      {open && (
        <ul
          ref={listRef}
          id="sg-autocomplete-list"
          className="absolute top-full left-0 right-0 mt-1 bg-(--sg-surface) border border-(--sg-border) rounded-[6px] shadow-[0_4px_16px_rgba(0,0,0,0.12)] max-h-[200px] overflow-y-auto z-100 p-0 m-0 list-none"
          role="listbox"
        >
          {filtered.length === 0 ? (
            <li className="px-3 py-2 text-xs text-(--sg-text-faint)" role="option" aria-disabled>No results</li>
          ) : (
            filtered.map((opt, i) => (
              <li
                key={String(opt.value)}
                className={`flex items-center justify-between px-3 py-1.5 text-xs cursor-pointer transition-colors ${i === activeIdx ? 'bg-(--sg-surface-raised)' : 'hover:bg-(--sg-surface-raised)'}`}
                role="option"
                aria-selected={opt.value === value}
                onMouseDown={e => { e.preventDefault(); select(opt); }}
                onMouseEnter={() => setActiveIdx(i)}
              >
                {renderOption ? renderOption(opt, i === activeIdx) : (
                  <span>{opt.label}</span>
                )}
                {opt.description && <span className="text-[10px] text-(--sg-text-faint) ml-auto shrink-0 pl-2">{opt.description}</span>}
              </li>
            ))
          )}
        </ul>
      )}
    </div>
  );
}
