// src/lib/components/ConfirmDialog.svelte
<script lang="ts">
  type Props = {
    title: string;
    message: string;
    confirmLabel?: string;
    cancelLabel?: string;
    danger?: boolean;
    onconfirm: () => void;
    oncancel: () => void;
  };

  const {
    title,
    message,
    confirmLabel = "Confirm",
    cancelLabel = "Cancel",
    danger = false,
    onconfirm,
    oncancel,
  }: Props = $props();

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") oncancel();
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  data-testid="confirm-dialog"
  class="fixed inset-0 z-50 flex items-center justify-center bg-black/40"
  style="animation: sg-fade-in 0.1s ease-out"
  onkeydown={handleKeydown}
  onmousedown={(e) => { if (e.target === e.currentTarget) oncancel(); }}
>
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class="w-full max-w-sm rounded-lg border border-[var(--sg-border)] bg-[var(--sg-surface)] p-4 shadow-2xl"
    style="animation: sg-slide-up 0.15s ease-out"
    onmousedown={(e) => e.stopPropagation()}
  >
    <h3 class="mb-1 text-sm font-semibold text-[var(--sg-text)]">{title}</h3>
    <p class="mb-4 text-xs leading-relaxed text-[var(--sg-text-dim)]">{message}</p>
    <div class="flex items-center justify-end gap-2">
      <button
        onclick={oncancel}
        data-testid="confirm-dialog-cancel"
        class="rounded px-3 py-1.5 text-xs text-[var(--sg-text-dim)] hover:bg-[var(--sg-surface-raised)] hover:text-[var(--sg-text)]"
      >
        {cancelLabel}
      </button>
      <button
        onclick={onconfirm}
        data-testid="confirm-dialog-confirm"
        class="rounded px-3 py-1.5 text-xs font-semibold {danger
          ? 'bg-[var(--sg-danger)] text-white hover:opacity-90'
          : 'bg-[var(--sg-primary)] text-[var(--sg-bg)] hover:bg-[var(--sg-primary-hover)]'}"
      >
        {confirmLabel}
      </button>
    </div>
  </div>
</div>

// packages/ui/src/components/ConfirmDialog.tsx
import { type ReactNode } from 'react';
import { Spinner } from './Spinner.js';

type Props = {
  title: string;
  message?: string;
  confirmLabel?: string;
  cancelLabel?: string;
  loading?: boolean;
  danger?: boolean;
  onConfirm: () => void;
  onCancel: () => void;
  children?: ReactNode;
};

/** Modal confirmation dialog. Rendered by the caller — wrap in a portal if needed. */
export function ConfirmDialog({
  title,
  message,
  confirmLabel = 'Confirm',
  cancelLabel = 'Cancel',
  loading = false,
  danger = false,
  onConfirm,
  onCancel,
  children,
}: Props) {
  const primaryBtn = 'inline-flex items-center gap-[5px] px-3 py-[5px] rounded-[6px] border-none cursor-pointer text-xs font-medium transition-colors whitespace-nowrap bg-(--sg-primary) text-white hover:bg-(--sg-primary-hover) disabled:opacity-50 disabled:cursor-not-allowed';
  const dangerBtn = 'inline-flex items-center gap-[5px] px-3 py-[5px] rounded-[6px] border-none cursor-pointer text-xs font-medium transition-colors whitespace-nowrap bg-(--sg-danger) text-white hover:opacity-85 disabled:opacity-50 disabled:cursor-not-allowed';
  const secondaryBtn = 'inline-flex items-center gap-[5px] px-3 py-[5px] rounded-[6px] cursor-pointer text-xs font-medium transition-colors whitespace-nowrap bg-transparent border border-(--sg-border) text-(--sg-text-dim) hover:bg-(--sg-surface-raised) disabled:opacity-50 disabled:cursor-not-allowed';

  return (
    <div className="fixed inset-0 z-200 bg-black/45 flex items-center justify-center" onClick={onCancel}>
      <div
        className="bg-(--sg-surface) border border-(--sg-border) rounded-[12px] p-6 min-w-[320px] max-w-[480px] shadow-[0_20px_60px_rgba(0,0,0,0.25)]"
        onClick={e => e.stopPropagation()}
        role="dialog"
        aria-modal
        aria-labelledby="sg-dialog-title"
      >
        <h2 id="sg-dialog-title" className="text-[15px] font-semibold m-0 mb-[10px] text-(--sg-text)">{title}</h2>
        {message && <p className="text-[13px] text-(--sg-text-dim) m-0 mb-4">{message}</p>}
        {children}
        <div className="flex gap-2 justify-end mt-5">
          <button className={secondaryBtn} onClick={onCancel} disabled={loading}>
            {cancelLabel}
          </button>
          <button
            className={danger ? dangerBtn : primaryBtn}
            onClick={onConfirm}
            disabled={loading}
          >
            {loading ? <Spinner size="sm" /> : confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
}
