// src/lib/components/Spinner.svelte
<script lang="ts">
  type Props = {
    size?: 'sm' | 'md' | 'lg';
    label?: string;
  };

  const { size = 'md', label }: Props = $props();

  const sizeMap = { sm: 'h-4 w-4', md: 'h-6 w-6', lg: 'h-8 w-8' };
</script>

<div data-testid="spinner" class="flex items-center justify-center gap-2">
  <svg
    class="{sizeMap[size]} text-[var(--sg-primary)]"
    style="animation: sg-spin 0.8s linear infinite"
    fill="none"
    viewBox="0 0 24 24"
  >
    <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3" opacity="0.2" />
    <path
      d="M12 2a10 10 0 0 1 10 10"
      stroke="currentColor"
      stroke-width="3"
      stroke-linecap="round"
    />
  </svg>
  {#if label}
    <span class="text-xs text-[var(--sg-text-faint)]">{label}</span>
  {/if}
</div>

// packages/ui/src/components/Spinner.tsx
type Size = 'sm' | 'md' | 'lg';

const sizes: Record<Size, number> = { sm: 12, md: 16, lg: 24 };

type Props = { size?: Size; className?: string };

/** Animated loading spinner that matches the old Svelte design. */
export function Spinner({ size = 'md', className }: Props) {
  const s = sizes[size];
  return (
    <svg
      width={s}
      height={s}
      viewBox="0 0 24 24"
      className={['sg-spinner', className].filter(Boolean).join(' ')}
      aria-label="Loading"
      role="status"
      style={{ animation: 'sg-spin 0.7s linear infinite' }}
    >
      <circle
        cx={12}
        cy={12}
        r={10}
        fill="none"
        stroke="currentColor"
        strokeWidth={2.5}
        strokeDasharray="40 22"
        strokeLinecap="round"
      />
    </svg>
  );
}
