// src/lib/components/WorkspaceHooksModal.svelte
<script lang="ts">
  import { fade, scale } from 'svelte/transition';
  import MonacoEditor from '$lib/components/MonacoEditor.svelte';
  import Spinner from '$lib/components/Spinner.svelte';
  import {
    createWorkspaceHook,
    deleteWorkspaceHook,
    listWorkspaceHooks,
    toggleWorkspaceHook,
    updateWorkspaceHook,
    type HookUpsertInput,
    type WorkspaceHook,
    type WorkspaceHookShell,
    type WorkspaceHookScope,
    type WorkspaceHookTrigger,
  } from '$lib/sproutgit';
  import { toast } from '$lib/toast.svelte';

  type Props = {
    open: boolean;
    workspacePath: string;
    onClose: () => void;
  };

  let { open, workspacePath, onClose }: Props = $props();

  const triggerOptions: WorkspaceHookTrigger[] = [
    'before_worktree_create',
    'after_worktree_create',
    'before_worktree_remove',
    'after_worktree_remove',
    'before_worktree_switch',
    'after_worktree_switch',
    'manual',
  ];

  let loading = $state(false);
  let saving = $state(false);
  let togglingHookId = $state<string | null>(null);
  let hooks = $state<WorkspaceHook[]>([]);

  let editorOpen = $state(false);
  let editingHookId = $state<string | null>(null);

  let detectedShell = $state<WorkspaceHookShell>('bash');
  let detectedShellLabel = $state('Linux (bash)');
  const scopeOptions: { value: WorkspaceHookScope; label: string; detail: string }[] = [
    {
      value: 'worktree',
      label: 'Worktree',
      detail: 'Use when the hook is specific to the worktree being acted on.',
    },
    {
      value: 'workspace',
      label: 'Workspace',
      detail: 'Use when the hook manages shared workspace resources or cross-worktree state.',
    },
  ];

  const hookVariableGroups = [
    {
      title: 'Workspace',
      items: [
        { name: 'SPROUTGIT_WORKSPACE_PATH', description: 'Absolute path to the SproutGit workspace.' },
        { name: 'SPROUTGIT_WORKSPACE_NAME', description: 'Workspace directory name.' },
        { name: 'SPROUTGIT_ROOT_PATH', description: 'Absolute path to the protected root checkout.' },
        { name: 'SPROUTGIT_WORKTREES_PATH', description: 'Absolute path to the managed worktrees directory.' },
      ],
    },
    {
      title: 'Worktree',
      items: [
        { name: 'SPROUTGIT_WORKTREE_PATH', description: 'Absolute path to the target worktree.' },
        { name: 'SPROUTGIT_WORKTREE_NAME', description: 'Target worktree directory name.' },
        { name: 'SPROUTGIT_WORKTREE_BRANCH', description: 'Current branch name, if attached.' },
        { name: 'SPROUTGIT_WORKTREE_HEAD', description: 'Full HEAD commit hash.' },
        { name: 'SPROUTGIT_WORKTREE_HEAD_SHORT', description: 'Short HEAD commit hash.' },
        { name: 'SPROUTGIT_WORKTREE_DETACHED', description: 'true when the worktree is in detached HEAD state.' },
      ],
    },
    {
      title: 'Trigger',
      items: [
        { name: 'SPROUTGIT_TRIGGER', description: 'Full trigger name, such as before_worktree_create.' },
        { name: 'SPROUTGIT_TRIGGER_PHASE', description: 'before or after.' },
        { name: 'SPROUTGIT_TRIGGER_ACTION', description: 'create, remove, or switch.' },
        { name: 'SPROUTGIT_OS', description: 'Current OS label: macos, linux, or windows.' },
      ],
    },
    {
      title: 'Hook',
      items: [
        { name: 'SPROUTGIT_HOOK_ID', description: 'Stable ID of the current hook.' },
        { name: 'SPROUTGIT_HOOK_NAME', description: 'Human-readable hook name.' },
        { name: 'SPROUTGIT_HOOK_SCOPE', description: 'Whether the hook is classified as worktree or workspace scoped.' },
        { name: 'SPROUTGIT_HOOK_SHELL', description: 'Shell used to execute the script.' },
        { name: 'SPROUTGIT_HOOK_CRITICAL', description: 'true when the hook is marked critical.' },
        { name: 'SPROUTGIT_HOOK_TIMEOUT_SECONDS', description: 'Configured timeout for this hook run.' },
      ],
    },
  ] as const;

  const defaultScript = () => `# Example: run project setup for this worktree\n# Workspace: $SPROUTGIT_WORKSPACE_NAME\n# Worktree: $SPROUTGIT_WORKTREE_PATH\n# Branch: $SPROUTGIT_WORKTREE_BRANCH\n# Trigger: $SPROUTGIT_TRIGGER\n# pnpm install\n# pnpm run db:migrate`;

  let form = $state<HookUpsertInput>({
    name: '',
    scope: 'worktree',
    trigger: 'before_worktree_create',
    shell: 'bash',
    script: defaultScript(),
    enabled: true,
    critical: false,
    timeoutSeconds: 600,
    dependencyIds: [],
  });

  function detectShellFromPlatform(): { shell: WorkspaceHookShell; label: string } {
    if (typeof navigator === 'undefined') {
      return { shell: 'bash', label: 'Linux (bash)' };
    }

    const ua = `${navigator.userAgent} ${navigator.platform}`.toLowerCase();
    if (ua.includes('win')) {
      return { shell: 'pwsh', label: 'Windows (pwsh)' };
    }
    if (ua.includes('mac')) {
      return { shell: 'zsh', label: 'macOS (zsh)' };
    }
    return { shell: 'bash', label: 'Linux (bash)' };
  }

  function applyDetectedShell() {
    const detected = detectShellFromPlatform();
    detectedShell = detected.shell;
    detectedShellLabel = detected.label;
  }

  function normalizeTriggerLabel(trigger: WorkspaceHookTrigger): string {
    return trigger.replaceAll('_', ' ');
  }

  async function loadHooks() {
    if (!workspacePath) return;
    loading = true;
    try {
      hooks = await listWorkspaceHooks(workspacePath);
    } catch (err) {
      toast.error(`Failed to load hooks: ${err}`);
    } finally {
      loading = false;
    }
  }

  function resetForm() {
    editingHookId = null;
    form = {
      name: '',
      scope: 'worktree',
      trigger: 'before_worktree_create',
      shell: detectedShell,
      script: defaultScript(),
      enabled: true,
      critical: false,
      timeoutSeconds: 600,
      dependencyIds: [],
    };
  }

  function openNewModal() {
    resetForm();
    editorOpen = true;
  }

  function openEditModal(hook: WorkspaceHook) {
    editingHookId = hook.id;
    form = {
      name: hook.name,
      scope: hook.scope,
      trigger: hook.trigger,
      shell: detectedShell,
      script: hook.script,
      enabled: hook.enabled,
      critical: hook.critical,
      timeoutSeconds: hook.timeoutSeconds,
      dependencyIds: [...hook.dependencyIds],
    };
    editorOpen = true;
  }

  async function saveHook() {
    if (!workspacePath) return;

    saving = true;
    const payload: HookUpsertInput = {
      ...form,
      shell: detectedShell,
    };

    try {
      if (editingHookId) {
        await updateWorkspaceHook(workspacePath, editingHookId, payload);
        toast.success('Hook updated');
      } else {
        await createWorkspaceHook(workspacePath, payload);
        toast.success('Hook created');
      }

      editorOpen = false;
      await loadHooks();
    } catch (err) {
      toast.error(String(err));
    } finally {
      saving = false;
    }
  }

  async function removeHook(hookId: string) {
    if (!workspacePath) return;
    saving = true;
    try {
      await deleteWorkspaceHook(workspacePath, hookId);
      toast.info('Hook removed');
      await loadHooks();
    } catch (err) {
      toast.error(String(err));
    } finally {
      saving = false;
    }
  }

  async function toggleEnabled(hook: WorkspaceHook) {
    if (!workspacePath) return;

    const next = !hook.enabled;
    hooks = hooks.map(item => (item.id === hook.id ? { ...item, enabled: next } : item));
    togglingHookId = hook.id;

    try {
      await toggleWorkspaceHook(workspacePath, hook.id, next);
    } catch (err) {
      hooks = hooks.map(item => (item.id === hook.id ? { ...item, enabled: hook.enabled } : item));
      toast.error(String(err));
    } finally {
      togglingHookId = null;
    }
  }

  function toggleDependency(hookId: string, checked: boolean) {
    const next = new Set(form.dependencyIds);
    if (checked) {
      next.add(hookId);
    } else {
      next.delete(hookId);
    }
    form = {
      ...form,
      dependencyIds: Array.from(next),
    };
  }

  let dependencyCandidates = $derived(
    hooks.filter(hook => hook.id !== editingHookId && hook.trigger === form.trigger)
  );

  $effect(() => {
    applyDetectedShell();
  });

  $effect(() => {
    if (!open || !workspacePath) return;
    void loadHooks();
  });
</script>

{#if open}
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div
    class="fixed inset-0 z-40 bg-black/40"
    transition:fade={{ duration: 180 }}
    onclick={onClose}
  ></div>

  <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
    <div
      class="flex h-[min(78vh,760px)] w-[min(900px,96vw)] flex-col overflow-hidden rounded-xl border border-[var(--sg-border)] bg-[var(--sg-surface)] shadow-xl"
      transition:scale={{ duration: 220, start: 0.97 }}
    >
      <div
        class="flex items-center justify-between border-b border-[var(--sg-border-subtle)] px-4 py-3"
      >
        <div>
          <p class="text-sm font-semibold text-[var(--sg-text)]">Workspace Hooks</p>
          <p class="text-xs text-[var(--sg-text-faint)]">
            Manage lifecycle hooks for this workspace.
          </p>
        </div>
        <div class="flex items-center gap-2">
          <button
            onclick={openNewModal}
            class="rounded border border-[var(--sg-border)] bg-[var(--sg-surface-raised)] px-3 py-1.5 text-xs text-[var(--sg-text)] hover:bg-[var(--sg-border)]"
            >New hook</button
          >
          <button
            onclick={onClose}
            class="rounded p-1 text-[var(--sg-text-faint)] hover:bg-[var(--sg-surface-raised)] hover:text-[var(--sg-text)]"
            aria-label="Close"
          >
            <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"
              ><path d="M18 6 6 18M6 6l12 12" stroke-width="2" stroke-linecap="round" /></svg
            >
          </button>
        </div>
      </div>

      <div class="min-h-0 flex-1 overflow-auto p-4">
        {#if loading}
          <div class="flex items-center gap-2 text-xs text-[var(--sg-text-dim)]">
            <Spinner size="sm" />
            Loading hooks…
          </div>
        {:else if hooks.length === 0}
          <div
            class="rounded-lg border border-[var(--sg-border)] bg-[var(--sg-surface-raised)] px-3 py-2 text-xs text-[var(--sg-text-dim)]"
          >
            No hooks defined yet. Create one to automate workspace setup or cleanup.
          </div>
        {:else}
          <div class="space-y-2">
            {#each hooks as hook}
              <div
                class="rounded-lg border border-[var(--sg-border-subtle)] bg-[var(--sg-surface-raised)] px-3 py-2.5 transition-all duration-300 ease-[cubic-bezier(0.22,1,0.36,1)] hover:-translate-y-0.5 hover:shadow-[0_10px_30px_-20px_rgba(0,0,0,0.55)]"
                transition:fade={{ duration: 180 }}
              >
                <div class="flex items-start justify-between gap-3">
                  <div class="min-w-0">
                    <p class="truncate text-sm font-medium text-[var(--sg-text)]">{hook.name}</p>
                    <p class="mt-0.5 text-xs text-[var(--sg-text-faint)]">
                      {normalizeTriggerLabel(hook.trigger)} • {hook.scope} • {hook.timeoutSeconds}s • {hook.shell}
                    </p>
                  </div>

                  <label class="inline-flex cursor-pointer items-center gap-2">
                    <input
                      type="checkbox"
                      class="sr-only"
                      checked={hook.enabled}
                      disabled={togglingHookId === hook.id}
                      onchange={() => toggleEnabled(hook)}
                    />
                    <span
                      class="inline-flex h-4 w-8 items-center rounded-full p-0.5 transition-all duration-500 ease-[cubic-bezier(0.22,1,0.36,1)] {hook.enabled
                        ? 'bg-[var(--sg-primary)] shadow-[0_0_0_1px_color-mix(in_oklab,var(--sg-primary)_60%,black)]'
                        : 'bg-[var(--sg-border)]'} {togglingHookId === hook.id ? 'opacity-80' : ''}"
                    >
                      <span
                        class="h-3 w-3 rounded-full bg-white shadow-sm transform-gpu will-change-transform transition-all duration-500 ease-[cubic-bezier(0.22,1,0.36,1)] {hook.enabled
                          ? 'scale-105'
                          : 'scale-100'}"
                        style="transform: translateX({hook.enabled ? '16px' : '0px'});"
                      ></span>
                    </span>
                    <span
                      class="text-xs text-[var(--sg-text-dim)] transition-opacity duration-300 {togglingHookId ===
                      hook.id
                        ? 'opacity-60'
                        : 'opacity-100'}">Enabled</span
                    >
                  </label>
                </div>

                <div class="mt-2 flex items-center justify-between gap-2">
                  <div class="flex items-center gap-2">
                    {#if hook.critical}
                      <span
                        class="rounded bg-[var(--sg-danger)]/15 px-2 py-0.5 text-[10px] font-medium text-[var(--sg-danger)]"
                        >Critical</span
                      >
                    {:else}
                      <span
                        class="rounded bg-[var(--sg-accent)]/15 px-2 py-0.5 text-[10px] font-medium text-[var(--sg-accent)]"
                        >Non-critical</span
                      >
                    {/if}

                    {#if hook.dependencyIds.length > 0}
                      <span
                        class="rounded bg-[var(--sg-surface)] px-2 py-0.5 text-[10px] text-[var(--sg-text-faint)]"
                      >
                        Depends on {hook.dependencyIds.length}
                      </span>
                    {/if}
                  </div>

                  <div class="flex items-center gap-1">
                    <button
                      onclick={() => openEditModal(hook)}
                      class="rounded border border-[var(--sg-border)] px-2 py-1 text-[10px] text-[var(--sg-text-dim)] transition-all duration-200 hover:-translate-y-px hover:bg-[var(--sg-surface)] hover:text-[var(--sg-text)]"
                      >Edit</button
                    >
                    <button
                      onclick={() => removeHook(hook.id)}
                      disabled={saving}
                      class="rounded border border-[var(--sg-border)] px-2 py-1 text-[10px] text-[var(--sg-danger)] transition-all duration-200 hover:-translate-y-px hover:bg-[var(--sg-danger)]/10 disabled:opacity-50"
                      >Delete</button
                    >
                  </div>
                </div>
              </div>
            {/each}
          </div>
        {/if}
      </div>
    </div>
  </div>
{/if}

{#if editorOpen}
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div
    class="fixed inset-0 z-[60] bg-black/45"
    transition:fade={{ duration: 180 }}
    onclick={() => (editorOpen = false)}
  ></div>

  <div class="fixed inset-0 z-[70] flex items-center justify-center p-4">
    <div
      class="flex h-[min(86vh,860px)] w-[min(980px,96vw)] flex-col overflow-hidden rounded-xl border border-[var(--sg-border)] bg-[var(--sg-surface)] shadow-2xl"
      transition:scale={{ duration: 220, start: 0.97 }}
    >
      <div
        class="flex items-center justify-between border-b border-[var(--sg-border-subtle)] px-4 py-3"
      >
        <div>
          <p class="text-sm font-semibold text-[var(--sg-text)]">
            {editingHookId ? 'Edit hook' : 'New hook'}
          </p>
          <p class="text-xs text-[var(--sg-text-faint)]">
            Shell is auto-detected for your platform: {detectedShellLabel}
          </p>
        </div>
        <button
          onclick={() => (editorOpen = false)}
          class="rounded p-1 text-[var(--sg-text-faint)] hover:bg-[var(--sg-surface-raised)] hover:text-[var(--sg-text)]"
          aria-label="Close"
        >
          <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"
            ><path d="M18 6 6 18M6 6l12 12" stroke-width="2" stroke-linecap="round" /></svg
          >
        </button>
      </div>

      <div class="min-h-0 flex-1 overflow-auto p-4">
        <div class="grid grid-cols-1 gap-3">
          <label class="text-xs text-[var(--sg-text-faint)]">
            Hook name
            <input
              bind:value={form.name}
              class="mt-1 w-full rounded border border-[var(--sg-input-border)] bg-[var(--sg-input-bg)] px-2.5 py-1.5 text-xs text-[var(--sg-text)] outline-none focus:border-[var(--sg-input-focus)]"
              placeholder="Prepare dependencies"
            />
          </label>

          <div class="grid grid-cols-1 gap-2 sm:grid-cols-2">
            <label class="text-xs text-[var(--sg-text-faint)]">
              Scope
              <div class="relative mt-1">
                <select
                  bind:value={form.scope}
                  class="w-full appearance-none rounded border border-[var(--sg-input-border)] bg-[var(--sg-input-bg)] px-2.5 py-1.5 pr-8 text-xs text-[var(--sg-text)] outline-none focus:border-[var(--sg-input-focus)]"
                >
                  {#each scopeOptions as scope}
                    <option value={scope.value}>{scope.label}</option>
                  {/each}
                </select>
                <svg class="pointer-events-none absolute right-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[var(--sg-text-faint)]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="m6 9 6 6 6-6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" /></svg>
              </div>
              <p class="mt-1 text-[10px] leading-relaxed text-[var(--sg-text-faint)]">
                {scopeOptions.find((scope) => scope.value === form.scope)?.detail}
              </p>
            </label>

            <label class="text-xs text-[var(--sg-text-faint)]">
              Trigger
              <div class="relative mt-1">
                <select
                  bind:value={form.trigger}
                  class="w-full appearance-none rounded border border-[var(--sg-input-border)] bg-[var(--sg-input-bg)] px-2.5 py-1.5 pr-8 text-xs text-[var(--sg-text)] outline-none focus:border-[var(--sg-input-focus)]"
                >
                  {#each triggerOptions as trigger}
                    <option value={trigger}>{normalizeTriggerLabel(trigger)}</option>
                  {/each}
                </select>
                <svg
                  class="pointer-events-none absolute right-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[var(--sg-text-faint)]"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  ><path
                    d="m6 9 6 6 6-6"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  /></svg
                >
              </div>
            </label>

            <label class="text-xs text-[var(--sg-text-faint)]">
              Timeout seconds
              <input
                type="number"
                min="1"
                max="86400"
                bind:value={form.timeoutSeconds}
                class="mt-1 w-full rounded border border-[var(--sg-input-border)] bg-[var(--sg-input-bg)] px-2.5 py-1.5 text-xs text-[var(--sg-text)] outline-none focus:border-[var(--sg-input-focus)]"
              />
            </label>
          </div>

          <div class="grid grid-cols-1 gap-2 sm:grid-cols-2">
            <label class="inline-flex cursor-pointer items-start gap-2">
              <input type="checkbox" class="sr-only" bind:checked={form.enabled} />
              <span
                class="mt-0.5 inline-flex h-4 w-4 items-center justify-center rounded border border-[var(--sg-input-border)] {form.enabled
                  ? 'border-[var(--sg-primary)] bg-[var(--sg-primary)]'
                  : 'bg-[var(--sg-input-bg)]'}"
              >
                {#if form.enabled}
                  <svg
                    class="h-3 w-3 text-white"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    ><path
                      d="m5 13 4 4L19 7"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    /></svg
                  >
                {/if}
              </span>
              <span>
                <span class="block text-xs text-[var(--sg-text)]">Enabled</span>
                <span class="block text-[10px] text-[var(--sg-text-faint)]"
                  >Disable to keep without running.</span
                >
              </span>
            </label>

            <label class="inline-flex cursor-pointer items-start gap-2">
              <input type="checkbox" class="sr-only" bind:checked={form.critical} />
              <span
                class="mt-0.5 inline-flex h-4 w-4 items-center justify-center rounded border border-[var(--sg-input-border)] {form.critical
                  ? 'border-[var(--sg-danger)] bg-[var(--sg-danger)]'
                  : 'bg-[var(--sg-input-bg)]'}"
              >
                {#if form.critical}
                  <svg
                    class="h-3 w-3 text-white"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    ><path
                      d="m5 13 4 4L19 7"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    /></svg
                  >
                {/if}
              </span>
              <span>
                <span class="block text-xs text-[var(--sg-text)]">Critical</span>
                <span class="block text-[10px] text-[var(--sg-text-faint)]"
                  >If this fails in a before_* trigger, the worktree operation is blocked.</span
                >
              </span>
            </label>
          </div>

          <div>
            <p class="mb-1 text-xs text-[var(--sg-text-faint)]">Depends on</p>
            {#if dependencyCandidates.length === 0}
              <div
                class="rounded border border-[var(--sg-border-subtle)] bg-[var(--sg-surface-raised)] px-2.5 py-2 text-xs text-[var(--sg-text-faint)]"
              >
                No hooks available for this trigger yet.
              </div>
            {:else}
              <div
                class="max-h-28 overflow-auto rounded border border-[var(--sg-border-subtle)] bg-[var(--sg-surface-raised)] p-2"
              >
                {#each dependencyCandidates as candidate}
                  {@const isChecked = form.dependencyIds.includes(candidate.id)}
                  <label
                    class="mb-1.5 inline-flex w-full cursor-pointer items-center gap-2 rounded px-1 py-1 hover:bg-[var(--sg-surface)]"
                  >
                    <input
                      type="checkbox"
                      class="sr-only"
                      checked={isChecked}
                      onchange={event =>
                        toggleDependency(
                          candidate.id,
                          (event.currentTarget as HTMLInputElement).checked
                        )}
                    />
                    <span
                      class="inline-flex h-4 w-4 items-center justify-center rounded border border-[var(--sg-input-border)] {isChecked
                        ? 'border-[var(--sg-primary)] bg-[var(--sg-primary)]'
                        : 'bg-[var(--sg-input-bg)]'}"
                    >
                      {#if isChecked}
                        <svg
                          class="h-3 w-3 text-white"
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                          ><path
                            d="m5 13 4 4L19 7"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          /></svg
                        >
                      {/if}
                    </span>
                    <span class="min-w-0 truncate text-xs text-[var(--sg-text-dim)]"
                      >{candidate.name}</span
                    >
                  </label>
                {/each}
              </div>
            {/if}
            <p class="mt-1 text-[10px] text-[var(--sg-text-faint)]">
              This hook runs only after all selected dependencies complete.
            </p>
          </div>

          <div>
            <p class="mb-1 text-xs text-[var(--sg-text-faint)]">Script</p>
            <MonacoEditor
              value={form.script}
              language={detectedShell === 'pwsh' ? 'powershell' : 'shell'}
              theme="auto"
              height="360px"
              onChange={next => {
                form = { ...form, script: next };
              }}
            />
            <div class="mt-3 rounded-lg border border-[var(--sg-border-subtle)] bg-[var(--sg-surface-raised)] p-3">
              <div class="flex items-start justify-between gap-3">
                <div>
                  <p class="text-xs font-medium text-[var(--sg-text)]">Available runtime variables</p>
                  <p class="mt-0.5 text-[10px] text-[var(--sg-text-faint)]">
                    These are injected into every hook process so scripts can adapt to the current workspace, worktree, trigger, and hook metadata.
                  </p>
                </div>
                <span class="rounded border border-[var(--sg-border)] bg-[var(--sg-surface)] px-2 py-0.5 text-[10px] text-[var(--sg-text-faint)]">
                  {detectedShell === 'pwsh' ? '$env:NAME' : '$NAME'}
                </span>
              </div>

              <div class="mt-3 grid gap-3 md:grid-cols-2">
                {#each hookVariableGroups as group}
                  <div class="rounded border border-[var(--sg-border)] bg-[var(--sg-surface)] p-2.5">
                    <p class="text-[10px] font-semibold uppercase tracking-wider text-[var(--sg-text-faint)]">{group.title}</p>
                    <div class="mt-2 space-y-2">
                      {#each group.items as item}
                        <div>
                          <p class="font-mono text-[10px] text-[var(--sg-text)]">{item.name}</p>
                          <p class="mt-0.5 text-[10px] leading-relaxed text-[var(--sg-text-dim)]">{item.description}</p>
                        </div>
                      {/each}
                    </div>
                  </div>
                {/each}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div
        class="flex items-center justify-end gap-2 border-t border-[var(--sg-border-subtle)] px-4 py-3"
      >
        <button
          onclick={() => (editorOpen = false)}
          class="rounded border border-[var(--sg-border)] px-3 py-1.5 text-xs text-[var(--sg-text-dim)] hover:bg-[var(--sg-surface-raised)]"
          >Cancel</button
        >
        <button
          onclick={saveHook}
          disabled={saving || !form.name.trim() || !form.script.trim()}
          class="rounded bg-[var(--sg-primary)] px-3 py-1.5 text-xs font-semibold text-white hover:bg-[var(--sg-primary-hover)] disabled:opacity-40"
        >
          {#if saving}
            Saving…
          {:else if editingHookId}
            Save hook
          {:else}
            Create hook
          {/if}
        </button>
      </div>
    </div>
  </div>
{/if}

// packages/ui/src/components/WorkspaceHooksModal.tsx
import { useEffect, useMemo, useState } from 'react';
import type {
  WorkspaceHook,
  WorkspaceHookTrigger,
  WorkspaceHookShell,
  HookExecutionTarget,
  WorkspaceHookScope,
} from '@sproutgit/types';
import { Spinner } from './Spinner.js';
import { Select } from './Select.js';
import { MonacoEditor } from './MonacoEditor.js';
import { X, Trash2, Plus, Circle, CircleDot, Clock3, TerminalSquare, ShieldAlert } from 'lucide-react';

const TRIGGER_OPTIONS: { value: WorkspaceHookTrigger; label: string }[] = [
  { value: 'before_worktree_create', label: 'Before worktree create' },
  { value: 'after_worktree_create', label: 'After worktree create' },
  { value: 'before_worktree_remove', label: 'Before worktree remove' },
  { value: 'after_worktree_remove', label: 'After worktree remove' },
  { value: 'before_worktree_switch', label: 'Before worktree switch' },
  { value: 'after_worktree_switch', label: 'After worktree switch' },
  { value: 'manual', label: 'Manual' },
];

function defaultScript(shell: WorkspaceHookShell): string {
  if (shell === 'pwsh' || shell === 'powershell') {
    return `# Workspace: $env:SPROUTGIT_WORKSPACE\n# Worktree:  $env:SPROUTGIT_WORKTREE\n# Trigger:   $env:SPROUTGIT_TRIGGER\n`;
  }
  return `#!/usr/bin/env ${shell === 'zsh' ? 'zsh' : 'bash'}\n# Workspace: $SPROUTGIT_WORKSPACE\n# Worktree:  $SPROUTGIT_WORKTREE\n# Trigger:   $SPROUTGIT_TRIGGER\n`;
}

function shellFromPath(path?: string): WorkspaceHookShell {
  if (!path) return 'bash';
  const lower = path.toLowerCase();
  if (lower.includes('pwsh')) return 'pwsh';
  if (lower.includes('powershell')) return 'powershell';
  if (lower.includes('zsh')) return 'zsh';
  if (lower.includes('bash')) return 'bash';
  return 'bash';
}

const EXECUTION_TARGET_OPTIONS: Array<{ value: HookExecutionTarget; label: string }> = [
  { value: 'trigger_worktree', label: 'Trigger worktree' },
  { value: 'initiating_worktree', label: 'Initiating worktree' },
  { value: 'workspace', label: 'Workspace root' },
];

const SCOPE_OPTIONS: Array<{ value: WorkspaceHookScope; label: string }> = [
  { value: 'worktree', label: 'Worktree' },
  { value: 'workspace', label: 'Workspace' },
];

const RUNTIME_VARIABLE_GROUPS: { label: string; vars: string[] }[] = [
  {
    label: 'Workspace',
    vars: [
      '$SPROUTGIT_WORKSPACE',
      '$SPROUTGIT_WORKSPACE_NAME',
      '$SPROUTGIT_ROOT_PATH',
      '$SPROUTGIT_WORKTREES_PATH',
    ],
  },
  {
    label: 'Worktree',
    vars: [
      '$SPROUTGIT_WORKTREE',
      '$SPROUTGIT_WORKTREE_NAME',
      '$SPROUTGIT_WORKTREE_BRANCH',
      '$SPROUTGIT_SOURCE_REF',
    ],
  },
  {
    label: 'Trigger',
    vars: [
      '$SPROUTGIT_TRIGGER',
      '$SPROUTGIT_INITIATING_WORKTREE',
    ],
  },
  {
    label: 'Hook',
    vars: [
      '$SPROUTGIT_HOOK_ID',
      '$SPROUTGIT_HOOK_NAME',
      '$SPROUTGIT_HOOK_SCOPE',
      '$SPROUTGIT_HOOK_SHELL',
      '$SPROUTGIT_HOOK_CRITICAL',
      '$SPROUTGIT_HOOK_TIMEOUT_SECONDS',
    ],
  },
  {
    label: 'System',
    vars: ['$SPROUTGIT_OS'],
  },
];

type HookApi = {
  listHooks: (workspacePath: string) => Promise<WorkspaceHook[]>;
  createHook: (args: {
    workspacePath: string;
    id: string;
    name: string;
    scope: WorkspaceHookScope;
    trigger: WorkspaceHookTrigger;
    shell: WorkspaceHookShell;
    executionTarget: HookExecutionTarget;
    script: string;
    enabled?: boolean;
    critical?: boolean;
    switchOncePerSession?: boolean;
    switchRunOnCreate?: boolean;
    switchRunOnDelete?: boolean;
    keepOpenOnCompletion?: boolean;
    timeoutSeconds?: number;
    dependencyIds?: string[];
  }) => Promise<void>;
  updateHook: (args: {
    workspacePath: string;
    id: string;
    name?: string;
    scope?: WorkspaceHookScope;
    trigger?: WorkspaceHookTrigger;
    executionTarget?: HookExecutionTarget;
    shell?: WorkspaceHookShell;
    script?: string;
    enabled?: boolean;
    critical?: boolean;
    switchOncePerSession?: boolean;
    switchRunOnCreate?: boolean;
    switchRunOnDelete?: boolean;
    keepOpenOnCompletion?: boolean;
    timeoutSeconds?: number;
    dependencyIds?: string[];
  }) => Promise<void>;
  deleteHook: (workspacePath: string, id: string) => Promise<void>;
  toggleHook: (workspacePath: string, id: string, enabled: boolean) => Promise<void>;
};

type Props = {
  open: boolean;
  workspacePath: string;
  api: HookApi;
  onClose: () => void;
  defaultShell?: string;
};

type Draft = {
  name: string;
  scope: WorkspaceHookScope;
  trigger: WorkspaceHookTrigger;
  shell: WorkspaceHookShell;
  executionTarget: HookExecutionTarget;
  dependencyIds: string[];
  script: string;
  enabled: boolean;
  critical: boolean;
  switchOncePerSession: boolean;
  switchRunOnCreate: boolean;
  switchRunOnDelete: boolean;
  keepOpenOnCompletion: boolean;
  timeoutSeconds: number;
};

const defaultDraft = (shell: WorkspaceHookShell = 'bash'): Draft => ({
  name: '',
  scope: 'worktree',
  trigger: 'after_worktree_create',
  shell,
  executionTarget: 'trigger_worktree',
  script: defaultScript(shell),
  enabled: true,
  critical: false,
  switchOncePerSession: false,
  switchRunOnCreate: true,
  switchRunOnDelete: false,
  keepOpenOnCompletion: false,
  timeoutSeconds: 60,
  dependencyIds: [],
});

function draftFromHook(hook: WorkspaceHook): Draft {
  return {
    name: hook.name,
    scope: hook.scope,
    trigger: hook.trigger,
    shell: hook.shell,
    executionTarget: hook.executionTarget,
    script: hook.script,
    enabled: hook.enabled,
    critical: hook.critical,
    switchOncePerSession: hook.switchOncePerSession ?? false,
    switchRunOnCreate: hook.switchRunOnCreate ?? true,
    switchRunOnDelete: hook.switchRunOnDelete ?? false,
    keepOpenOnCompletion: hook.keepOpenOnCompletion ?? false,
    timeoutSeconds: hook.timeoutSeconds ?? 60,
    dependencyIds: hook.dependencyIds ?? [],
  };
}

function isSwitchTrigger(trigger: WorkspaceHookTrigger): boolean {
  return trigger === 'before_worktree_switch' || trigger === 'after_worktree_switch';
}

function triggerLabel(trigger: WorkspaceHookTrigger): string {
  return TRIGGER_OPTIONS.find(option => option.value === trigger)?.label ?? trigger;
}

function executionTargetLabel(target: HookExecutionTarget): string {
  return EXECUTION_TARGET_OPTIONS.find(option => option.value === target)?.label ?? target;
}

export function WorkspaceHooksModal({ open, workspacePath, api, onClose, defaultShell }: Props) {
  const [hooks, setHooks] = useState<WorkspaceHook[]>([]);
  const [loading, setLoading] = useState(false);
  const [editing, setEditing] = useState<{ hook: WorkspaceHook; draft: Draft } | null>(null);
  const [creating, setCreating] = useState<Draft | null>(null);
  const [savingDraft, setSavingDraft] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  useEffect(() => {
    if (!open) return;
    setLoading(true);
    void api.listHooks(workspacePath)
      .then(setHooks)
      .finally(() => setLoading(false));
  }, [open, workspacePath, api]);

  const groupedHooks = useMemo(() => {
    const map = new Map<WorkspaceHookTrigger, WorkspaceHook[]>();
    for (const trigger of TRIGGER_OPTIONS) map.set(trigger.value, []);
    for (const hook of hooks) {
      const list = map.get(hook.trigger);
      if (list) list.push(hook);
    }
    return map;
  }, [hooks]);

  if (!open) return null;

  /** Persists the current draft (create or edit) if the name is non-empty. */
  async function saveDraftIfNeeded(): Promise<void> {
    if (creating && creating.name.trim()) {
      await api.createHook({
        workspacePath,
        id: self.crypto.randomUUID(),
        name: creating.name,
        scope: creating.scope,
        trigger: creating.trigger,
        shell: creating.shell,
        executionTarget: creating.executionTarget,
        script: creating.script,
        enabled: creating.enabled,
        critical: creating.critical,
        switchOncePerSession: creating.switchOncePerSession,
        switchRunOnCreate: creating.switchRunOnCreate,
        switchRunOnDelete: creating.switchRunOnDelete,
        keepOpenOnCompletion: creating.keepOpenOnCompletion,
        timeoutSeconds: creating.timeoutSeconds,
        dependencyIds: creating.dependencyIds,
      });
    } else if (editing && editing.draft.name.trim()) {
      await api.updateHook({
        workspacePath,
        id: editing.hook.id,
        name: editing.draft.name,
        scope: editing.draft.scope,
        trigger: editing.draft.trigger,
        executionTarget: editing.draft.executionTarget,
        shell: editing.draft.shell,
        script: editing.draft.script,
        enabled: editing.draft.enabled,
        critical: editing.draft.critical,
        switchOncePerSession: editing.draft.switchOncePerSession,
        switchRunOnCreate: editing.draft.switchRunOnCreate,
        switchRunOnDelete: editing.draft.switchRunOnDelete,
        keepOpenOnCompletion: editing.draft.keepOpenOnCompletion,
        timeoutSeconds: editing.draft.timeoutSeconds,
        dependencyIds: editing.draft.dependencyIds,
      });
    }
  }

  /** Auto-saves the current draft, then closes the modal. */
  async function handleClose() {
    setSavingDraft(true);
    setSaveError(null);
    try {
      await saveDraftIfNeeded();
      onClose();
    } catch (err) {
      setSaveError(String(err));
    } finally {
      setSavingDraft(false);
    }
  }

  /** Auto-saves the current draft, then switches to the given hook. */
  async function selectHookItem(hook: WorkspaceHook) {
    setSavingDraft(true);
    setSaveError(null);
    try {
      await saveDraftIfNeeded();
      const updated = await api.listHooks(workspacePath);
      setHooks(updated);
      setCreating(null);
      const fresh = updated.find(h => h.id === hook.id) ?? hook;
      setEditing({ hook: fresh, draft: draftFromHook(fresh) });
    } catch (err) {
      setSaveError(String(err));
    } finally {
      setSavingDraft(false);
    }
  }

  /** Auto-saves the current draft, then opens the new-hook form. */
  async function handleNewHook() {
    setSavingDraft(true);
    setSaveError(null);
    try {
      await saveDraftIfNeeded();
      const updated = await api.listHooks(workspacePath).catch(() => hooks);
      setHooks(updated);
      setEditing(null);
      setCreating(defaultDraft(shellFromPath(defaultShell)));
    } catch (err) {
      setSaveError(String(err));
    } finally {
      setSavingDraft(false);
    }
  }

  async function toggleHook(hook: WorkspaceHook) {
    await api.toggleHook(workspacePath, hook.id, !hook.enabled);
    const updated = await api.listHooks(workspacePath);
    setHooks(updated);
    // Keep the editor draft in sync with the toggled state.
    if (editing?.hook.id === hook.id) {
      setEditing(e => e ? {
        ...e,
        hook: { ...e.hook, enabled: !hook.enabled },
        draft: { ...e.draft, enabled: !hook.enabled },
      } : null);
    }
  }

  async function deleteHook(id: string) {
    await api.deleteHook(workspacePath, id);
    const updated = await api.listHooks(workspacePath);
    setHooks(updated);
    if (editing?.hook.id === id) setEditing(null);
  }

  const activeDraft = creating ?? editing?.draft ?? null;

  function updateDraft(patch: Partial<Draft>) {
    if (creating) setCreating(d => d ? { ...d, ...patch } : null);
    else if (editing) setEditing(e => e ? { ...e, draft: { ...e.draft, ...patch } } : null);
  }

  const shellOptions: { value: WorkspaceHookShell; label: string }[] = [
    { value: 'bash', label: 'bash' },
    { value: 'zsh', label: 'zsh' },
    { value: 'pwsh', label: 'pwsh' },
    { value: 'powershell', label: 'powershell' },
  ];

  const secondaryBtn = 'inline-flex items-center gap-[5px] px-3 py-[5px] rounded-[6px] cursor-pointer text-xs font-medium transition-colors whitespace-nowrap bg-transparent border border-(--sg-border) text-(--sg-text-dim) hover:bg-(--sg-surface-raised) disabled:opacity-50 disabled:cursor-not-allowed';
  const iconBtn = 'inline-flex items-center justify-center p-[3px] bg-transparent border-none cursor-pointer text-(--sg-text-faint) rounded-[4px] transition-colors hover:text-(--sg-text) hover:bg-(--sg-surface-raised)';
  const fieldLabel = 'text-[11px] font-semibold text-(--sg-text-dim) uppercase tracking-[0.04em]';
  const fieldInput = 'w-full px-[10px] py-[6px] bg-(--sg-input-bg) border border-(--sg-input-border) rounded-[6px] text-xs text-(--sg-text) outline-none focus:border-(--sg-input-focus)';
  const sectionCard = 'rounded-lg border border-(--sg-border-subtle) bg-(--sg-surface-subtle) p-3 flex flex-col gap-2';

  return (
    <div className="fixed inset-0 z-200 bg-black/45 flex items-center justify-center" onClick={() => void handleClose()}>
      <div
        className="bg-(--sg-surface) border border-(--sg-border) rounded-xl shadow-[0_20px_60px_rgba(0,0,0,0.25)] flex flex-col overflow-hidden"
        style={{ minWidth: 560, maxWidth: 1100, width: '92vw', maxHeight: '88vh' }}
        onClick={e => e.stopPropagation()}
        role="dialog"
        aria-modal
        aria-label="Manage hooks"
      >
        <div className="px-5 py-4 border-b border-(--sg-border) shrink-0 bg-linear-to-r from-[rgba(25,172,92,0.12)] to-transparent">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h2 className="text-[15px] font-semibold m-0 text-(--sg-text)">Workspace Hooks</h2>
              <p className="m-0 mt-1 text-xs text-(--sg-text-dim)">
                Configure lifecycle automation for create, switch, remove, and manual operations.
              </p>
            </div>
            <div className="flex items-center gap-2 shrink-0">
              <button
                className={secondaryBtn}
                disabled={savingDraft}
                onClick={() => void handleNewHook()}
              >
                <Plus size={12} /> New hook
              </button>
              <button className={iconBtn} disabled={savingDraft} onClick={() => void handleClose()}>
                <X size={14} />
              </button>
            </div>
          </div>
        </div>

        <div className="flex flex-1 overflow-hidden">
          <div className="w-[260px] shrink-0 border-r border-(--sg-border) overflow-y-auto flex flex-col p-3 gap-3">
            {loading && <div className="p-3"><Spinner /></div>}
            {!loading && hooks.length === 0 && (
              <div className="rounded-lg border border-dashed border-(--sg-border) p-3">
                <p className="text-xs text-(--sg-text-faint) m-0">No hooks yet. Create your first hook to automate workspace actions.</p>
              </div>
            )}
            {!loading && TRIGGER_OPTIONS.map(section => {
              const sectionHooks = groupedHooks.get(section.value) ?? [];
              if (sectionHooks.length === 0) return null;

              return (
                <div key={section.value} className="flex flex-col gap-1.5">
                  <div className="px-1 text-[10px] font-semibold tracking-[0.08em] uppercase text-(--sg-text-faint)">
                    {section.label}
                  </div>
                  {sectionHooks.map(hook => (
                    <div
                      key={hook.id}
                      className={`rounded-lg border px-3 py-2 cursor-pointer text-xs transition-colors ${editing?.hook.id === hook.id ? 'border-(--sg-primary) bg-[rgba(25,172,92,0.1)]' : 'border-(--sg-border-subtle) bg-(--sg-surface) hover:bg-(--sg-surface-raised)'}`}
                      onClick={() => void selectHookItem(hook)}
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0">
                          <div className="font-medium text-(--sg-text) truncate">{hook.name}</div>
                          <div className="mt-1 text-[10px] text-(--sg-text-faint) flex items-center gap-1.5">
                            <TerminalSquare size={10} />
                            <span>{hook.shell}</span>
                            <span>•</span>
                            <span>{executionTargetLabel(hook.executionTarget)}</span>
                          </div>
                        </div>
                        <div className="flex items-center gap-1 shrink-0" onClick={e => e.stopPropagation()}>
                          <button
                            className={iconBtn}
                            onClick={() => void toggleHook(hook)}
                            title={hook.enabled ? 'Disable' : 'Enable'}
                          >
                            {hook.enabled ? <CircleDot size={12} /> : <Circle size={12} />}
                          </button>
                          <button
                            className="inline-flex items-center justify-center p-[3px] bg-transparent border-none cursor-pointer text-(--sg-danger) rounded-[4px] hover:bg-(--sg-surface-raised)"
                            onClick={() => void deleteHook(hook.id)}
                            title="Delete hook"
                          >
                            <Trash2 size={12} />
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              );
            })}
          </div>

          {activeDraft && (
            <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-3">
              <div className={sectionCard}>
                <div className="text-xs font-semibold text-(--sg-text)">Identity</div>
                <div className="flex flex-col gap-1">
                  <label className={fieldLabel}>Name</label>
                  <input
                    className={fieldInput}
                    value={activeDraft.name}
                    onChange={e => updateDraft({ name: e.target.value })}
                    placeholder="e.g. Install dependencies"
                  />
                </div>
                <div className="flex flex-col gap-1">
                  <label className={fieldLabel}>Scope</label>
                  <Select
                    value={activeDraft.scope}
                    options={SCOPE_OPTIONS}
                    onChange={value => updateDraft({ scope: value })}
                  />
                </div>
              </div>

              <div className={sectionCard}>
                <div className="text-xs font-semibold text-(--sg-text)">When and where</div>
                <div className="grid grid-cols-2 gap-3">
                  <div className="flex flex-col gap-1">
                    <label className={fieldLabel}>Trigger</label>
                    <Select
                      value={activeDraft.trigger}
                      options={TRIGGER_OPTIONS}
                      onChange={value => updateDraft({ trigger: value })}
                    />
                  </div>
                  <div className="flex flex-col gap-1">
                    <label className={fieldLabel}>Execution target</label>
                    <Select
                      value={activeDraft.executionTarget}
                      options={EXECUTION_TARGET_OPTIONS}
                      onChange={value => updateDraft({ executionTarget: value })}
                    />
                  </div>
                  <div className="flex flex-col gap-1">
                    <label className={fieldLabel}>Shell</label>
                    <Select
                      value={activeDraft.shell}
                      options={shellOptions}
                      onChange={value => updateDraft({ shell: value })}
                    />
                  </div>
                  <div className="flex flex-col gap-1">
                    <label className={fieldLabel}>Timeout (seconds)</label>
                    <div className="relative">
                      <Clock3 className="absolute left-2.5 top-1/2 -translate-y-1/2 text-(--sg-text-faint)" size={12} />
                      <input
                        className={`${fieldInput} pl-7`}
                        type="number"
                        min={1}
                        max={3600}
                        value={activeDraft.timeoutSeconds}
                        onChange={e => updateDraft({ timeoutSeconds: Number(e.target.value) })}
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div className={sectionCard}>
                <div className="text-xs font-semibold text-(--sg-text)">Behavior</div>
                <div className="grid grid-cols-2 gap-2">
                  <label className="flex items-center gap-1.5 text-xs text-(--sg-text-dim) cursor-pointer">
                    <input
                      type="checkbox"
                      checked={activeDraft.enabled}
                      onChange={e => updateDraft({ enabled: e.target.checked })}
                    />
                    Enabled
                  </label>
                  <label className="flex items-center gap-1.5 text-xs text-(--sg-text-dim) cursor-pointer">
                    <input
                      type="checkbox"
                      checked={activeDraft.keepOpenOnCompletion}
                      onChange={e => updateDraft({ keepOpenOnCompletion: e.target.checked })}
                    />
                    Keep terminal open on completion
                  </label>
                  <label className="flex items-center gap-1.5 text-xs text-(--sg-text-dim) cursor-pointer col-span-2">
                    <input
                      type="checkbox"
                      checked={activeDraft.critical}
                      onChange={e => updateDraft({ critical: e.target.checked })}
                    />
                    <ShieldAlert size={12} />
                    Critical hook (operation fails if this hook fails)
                  </label>
                </div>
                {isSwitchTrigger(activeDraft.trigger) && (
                  <div className="mt-1 grid grid-cols-1 gap-2 border-t border-(--sg-border-subtle) pt-2">
                    <label className="flex items-center gap-1.5 text-xs text-(--sg-text-dim) cursor-pointer">
                      <input
                        type="checkbox"
                        checked={activeDraft.switchOncePerSession}
                        onChange={e => updateDraft({ switchOncePerSession: e.target.checked })}
                      />
                      Run once per session
                    </label>
                    <label className="flex items-center gap-1.5 text-xs text-(--sg-text-dim) cursor-pointer">
                      <input
                        type="checkbox"
                        checked={activeDraft.switchRunOnCreate}
                        onChange={e => updateDraft({ switchRunOnCreate: e.target.checked })}
                      />
                      Run on create operations
                    </label>
                    <label className="flex items-center gap-1.5 text-xs text-(--sg-text-dim) cursor-pointer">
                      <input
                        type="checkbox"
                        checked={activeDraft.switchRunOnDelete}
                        onChange={e => updateDraft({ switchRunOnDelete: e.target.checked })}
                      />
                      Run on delete operations
                    </label>
                  </div>
                )}
              </div>

              {(() => {
                const sameTriggerHooks = hooks.filter(h =>
                  h.trigger === activeDraft.trigger &&
                  h.id !== (editing?.hook.id ?? ''),
                );
                if (sameTriggerHooks.length === 0) return null;
                return (
                  <div className={sectionCard}>
                    <div className="text-xs font-semibold text-(--sg-text)">Run after</div>
                    <p className="text-[11px] text-(--sg-text-faint) m-0">
                      This hook will wait for the selected hooks to complete first.
                    </p>
                    <div className="flex flex-col gap-1.5">
                      {sameTriggerHooks.map(h => (
                        <label key={h.id} className="flex items-center gap-2 text-xs text-(--sg-text-dim) cursor-pointer">
                          <input
                            type="checkbox"
                            checked={activeDraft.dependencyIds.includes(h.id)}
                            onChange={e => {
                              const next = e.target.checked
                                ? [...activeDraft.dependencyIds, h.id]
                                : activeDraft.dependencyIds.filter(id => id !== h.id);
                              updateDraft({ dependencyIds: next });
                            }}
                          />
                          <span className="truncate">{h.name}</span>
                          <span className="text-[10px] text-(--sg-text-faint) shrink-0">{h.shell}</span>
                        </label>
                      ))}
                    </div>
                  </div>
                );
              })()}

              <div className={sectionCard}>
                <div className="flex items-center justify-between gap-2">
                  <div className="text-xs font-semibold text-(--sg-text)">Script</div>
                  <div className="text-[10px] text-(--sg-text-faint)">{triggerLabel(activeDraft.trigger)}</div>
                </div>
                <MonacoEditor
                  value={activeDraft.script}
                  language={activeDraft.shell === 'pwsh' || activeDraft.shell === 'powershell' ? 'powershell' : 'shell'}
                  height="300px"
                  onChange={next => updateDraft({ script: next })}
                />
                <div className="rounded-md border border-(--sg-border-subtle) bg-(--sg-surface) px-2 py-1.5">
                  <div className="text-[10px] font-semibold uppercase tracking-[0.08em] text-(--sg-text-faint)">
                    Runtime variables
                  </div>
                  <div className="mt-1.5 flex flex-col gap-2">
                    {RUNTIME_VARIABLE_GROUPS.map(group => (
                      <div key={group.label}>
                        <div className="text-[9px] font-semibold uppercase tracking-[0.08em] text-(--sg-text-faint) mb-1">
                          {group.label}
                        </div>
                        <div className="flex flex-wrap gap-1">
                          {group.vars.map(variable => (
                            <span key={variable} className="text-[10px] px-1.5 py-0.5 rounded bg-(--sg-surface-raised) text-(--sg-text-dim) font-mono">
                              {variable}
                            </span>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {saveError && (
                <div className="flex items-center justify-between gap-2 rounded-md border border-(--sg-danger)/30 bg-(--sg-danger)/10 px-3 py-2">
                  <p className="text-[11px] text-(--sg-danger) m-0">{saveError}</p>
                  <button className={iconBtn} onClick={() => setSaveError(null)}><X size={12} /></button>
                </div>
              )}
              {!activeDraft.name.trim() && (
                <p className="text-[11px] text-(--sg-text-faint) m-0 text-right">
                  Add a name above to save this hook.
                </p>
              )}
            </div>
          )}

          {!activeDraft && (
            <div className="flex-1 p-6 text-xs text-(--sg-text-faint) flex items-center justify-center">
              Select a hook from the left or create a new one.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
