// packages/ui/src/components/ResizableSidebar.tsx
import { useRef, useState } from 'react';

type Props = {
  /** Starting width in pixels. */
  initialWidth?: number;
  minWidth?: number;
  maxWidth?: number;
  side?: 'left' | 'right';
  children: React.ReactNode;
  className?: string;
};

/**
 * A panel with a drag handle that lets the user resize it horizontally.
 * Works for both left and right sidebars.
 */
export function ResizableSidebar({
  initialWidth = 240,
  minWidth = 160,
  maxWidth = 600,
  side = 'left',
  children,
  className,
}: Props) {
  const [width, setWidth] = useState(initialWidth);
  const dragging = useRef(false);
  const startX = useRef(0);
  const startWidth = useRef(0);

  function onMouseDown(e: React.MouseEvent) {
    e.preventDefault();
    dragging.current = true;
    startX.current = e.clientX;
    startWidth.current = width;

    const onMove = (ev: MouseEvent) => {
      if (!dragging.current) return;
      const delta = side === 'left' ? ev.clientX - startX.current : startX.current - ev.clientX;
      const next = Math.min(maxWidth, Math.max(minWidth, startWidth.current + delta));
      setWidth(next);
    };

    const onUp = () => {
      dragging.current = false;
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
    };

    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
  }

  return (
    <div
      className={['relative flex shrink-0', className].filter(Boolean).join(' ')}
      style={{ width, minWidth: 0 }}
    >
      {side === 'right' && (
        <div
          className="absolute top-0 bottom-0 left-0 w-1 cursor-col-resize hover:bg-(--sg-primary) active:bg-(--sg-primary) z-10 transition-colors"
          onMouseDown={onMouseDown}
          role="separator"
          aria-orientation="vertical"
          aria-label="Resize sidebar"
        />
      )}
      <div className="flex-1 overflow-hidden">{children}</div>
      {side === 'left' && (
        <div
          className="absolute top-0 bottom-0 right-0 w-1 cursor-col-resize hover:bg-(--sg-primary) active:bg-(--sg-primary) z-10 transition-colors"
          onMouseDown={onMouseDown}
          role="separator"
          aria-orientation="vertical"
          aria-label="Resize sidebar"
        />
      )}
    </div>
  );
}

// src/lib/components/ResizableSidebar.svelte
<script lang="ts">
  import { onMount, untrack } from 'svelte';

  type Props = {
    /** Stable key used for localStorage persistence. */
    storageKey: string;
    /** Initial width in pixels (used when nothing is persisted yet). */
    defaultWidth?: number;
    /** Minimum width in pixels. */
    minWidth?: number;
    /** Maximum width in pixels. */
    maxWidth?: number;
    /** Side the resize handle sits on. Defaults to 'right' (sidebar on the left). */
    side?: 'right' | 'left';
    children: import('svelte').Snippet;
  };

  const {
    storageKey,
    defaultWidth = 320,
    minWidth = 240,
    maxWidth = 560,
    side = 'right',
    children,
  }: Props = $props();

  let width = $state(untrack(() => defaultWidth));
  let dragging = $state(false);
  let dragStartX = 0;
  let dragStartWidth = 0;

  const STORAGE_PREFIX = 'sg.sidebarWidth.';

  onMount(() => {
    try {
      const raw = localStorage.getItem(STORAGE_PREFIX + storageKey);
      if (raw) {
        const parsed = parseInt(raw, 10);
        if (Number.isFinite(parsed)) {
          width = Math.min(maxWidth, Math.max(minWidth, parsed));
        }
      }
    } catch {
      // localStorage unavailable; use default.
    }
  });

  function persist() {
    try {
      localStorage.setItem(STORAGE_PREFIX + storageKey, String(Math.round(width)));
    } catch {
      // ignore quota / privacy errors
    }
  }

  function onPointerDown(event: PointerEvent) {
    event.preventDefault();
    dragging = true;
    dragStartX = event.clientX;
    dragStartWidth = width;
    (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
  }

  function onPointerMove(event: PointerEvent) {
    if (!dragging) return;
    const delta = event.clientX - dragStartX;
    const next = side === 'right' ? dragStartWidth + delta : dragStartWidth - delta;
    width = Math.min(maxWidth, Math.max(minWidth, next));
  }

  function onPointerUp(event: PointerEvent) {
    if (!dragging) return;
    dragging = false;
    try {
      (event.currentTarget as HTMLElement).releasePointerCapture(event.pointerId);
    } catch {
      // pointer may already be released
    }
    persist();
  }

  function onDoubleClick() {
    width = defaultWidth;
    persist();
  }
</script>

<div
  class="relative flex shrink-0 flex-col"
  style:width="{width}px"
  style:user-select={dragging ? 'none' : ''}
>
  {@render children()}

  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class="group absolute top-0 bottom-0 z-20 flex w-2 cursor-col-resize items-stretch {side ===
    'right'
      ? '-right-1'
      : '-left-1'}"
    onpointerdown={onPointerDown}
    onpointermove={onPointerMove}
    onpointerup={onPointerUp}
    onpointercancel={onPointerUp}
    ondblclick={onDoubleClick}
    title="Drag to resize · double-click to reset"
    role="separator"
    aria-orientation="vertical"
    aria-valuenow={width}
    aria-valuemin={minWidth}
    aria-valuemax={maxWidth}
  >
    <div
      class="m-auto h-12 w-[2px] rounded-full transition-colors {dragging
        ? 'bg-[var(--sg-primary)]/70'
        : 'bg-transparent group-hover:bg-[var(--sg-primary)]/50'}"
    ></div>
  </div>
</div>
