// packages/ui/src/components/Select.tsx
type Option<T extends string = string> = {
  value: T;
  label: string;
  disabled?: boolean;
};

type Props<T extends string = string> = {
  value: T;
  options: Option<T>[];
  onChange: (value: T) => void;
  placeholder?: string;
  disabled?: boolean;
  label?: string;
  id?: string;
};

export function Select<T extends string = string>({
  value,
  options,
  onChange,
  placeholder,
  disabled = false,
  label,
  id,
}: Props<T>) {
  const selectId = id ?? `sg-select-${Math.random().toString(36).slice(2)}`;
  return (
    <div className="flex flex-col gap-1 w-full">
      {label && <label htmlFor={selectId} className="text-[11px] font-semibold text-(--sg-text-dim) uppercase tracking-[0.04em]">{label}</label>}
      <select
        id={selectId}
        className="w-full px-[10px] py-[6px] bg-(--sg-input-bg) border border-(--sg-input-border) rounded-[6px] text-xs text-(--sg-text) outline-none focus:border-(--sg-input-focus) cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
        value={value}
        onChange={e => onChange(e.target.value as T)}
        disabled={disabled}
      >
        {placeholder && (
          <option value="" disabled>{placeholder}</option>
        )}
        {options.map(opt => (
          <option key={opt.value} value={opt.value} disabled={opt.disabled}>
            {opt.label}
          </option>
        ))}
      </select>
    </div>
  );
}

// src/lib/components/Select.svelte
<script lang="ts">
  type SelectOption = {
    value: string;
    label: string;
  };

  type Props = {
    value: string;
    options: SelectOption[];
    disabled?: boolean;
    className?: string;
    onChange?: (value: string) => void;
  };

  let {
    value,
    options,
    disabled = false,
    className = '',
    onChange,
  }: Props = $props();

  function handleChange(event: Event) {
    const next = (event.currentTarget as HTMLSelectElement).value;
    onChange?.(next);
  }
</script>

<div class={`relative ${className}`}>
  <select
    value={value}
    disabled={disabled}
    class="w-full appearance-none rounded border border-[var(--sg-input-border)] bg-[var(--sg-input-bg)] px-2.5 py-1.5 pr-8 text-xs text-[var(--sg-text)] outline-none focus:border-[var(--sg-input-focus)] disabled:opacity-60"
    onchange={handleChange}
  >
    {#each options as option}
      <option value={option.value}>{option.label}</option>
    {/each}
  </select>
  <svg
    class="pointer-events-none absolute right-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[var(--sg-text-faint)]"
    fill="none"
    stroke="currentColor"
    viewBox="0 0 24 24"
  >
    <path
      d="m6 9 6 6 6-6"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
  </svg>
</div>
