// packages/ui/src/components/WindowControls.tsx
import { useEffect, useState } from 'react';
import { Minus, Square, Minimize2, X } from 'lucide-react';

/**
 * Window controls component.
 *
 * - macOS: the OS renders the native traffic-light buttons inside the
 *   `hiddenInset` title bar. This component reserves the inset space so
 *   content doesn't overlap the native controls. It renders nothing interactive.
 *
 * - Windows / Linux: renders custom minimize / maximize / close buttons
 *   via Electron's IPC (window:minimize, window:maximize, window:close).
 */
export function WindowControls() {
  const isMac = typeof navigator !== 'undefined' &&
    navigator.userAgent.toLowerCase().includes('mac');

  const [isMaximized, setIsMaximized] = useState(false);

  useEffect(() => {
    if (isMac) return;

    // Sync initial state.
    void window.api.windowIsMaximized().then(setIsMaximized).catch(() => undefined);

    const offMax = window.api.onWindowMaximized(() => setIsMaximized(true));
    const offUnmax = window.api.onWindowUnmaximized(() => setIsMaximized(false));
    return () => { offMax(); offUnmax(); };
  }, [isMac]);

  if (isMac) {
    // Reserve the macOS traffic-light inset area (drag region).
    return (
      <div
        className="shrink-0 h-(--sg-titlebar-height)"
        style={{ width: 'var(--sg-titlebar-inset, 85px)', WebkitAppRegion: 'drag' } as React.CSSProperties}
        aria-hidden
      />
    );
  }

  const winBtn = 'flex items-center justify-center w-11 h-full bg-transparent border-none cursor-pointer text-(--sg-text-dim) transition-colors hover:bg-(--sg-surface-raised) hover:text-(--sg-text)';

  return (
    <div
      className="flex items-stretch h-(--sg-titlebar-height) shrink-0"
      style={{ WebkitAppRegion: 'no-drag' } as React.CSSProperties}
      role="toolbar"
      aria-label="Window controls"
    >
      <button className={winBtn} title="Minimize" onClick={() => void window.api.windowMinimize()}>
        <Minus size={14} />
      </button>
      <button className={winBtn} title={isMaximized ? 'Restore' : 'Maximize'} onClick={() => void window.api.windowMaximize()}>
        {isMaximized ? <Minimize2 size={14} /> : <Square size={14} />}
      </button>
      <button
        className={`${winBtn} hover:!bg-(--sg-danger) hover:!text-white`}
        title="Close"
        onClick={() => void window.api.windowClose()}
      >
        <X size={14} />
      </button>
    </div>
  );
}

// src/lib/components/WindowControls.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { getCurrentWindow } from '@tauri-apps/api/window';
  import { Minus, Square, Minimize2, X } from 'lucide-svelte';

  let isWindows = $state(false);
  let isMaximized = $state(false);
  let unlistenResize: (() => void) | undefined;

  onMount(async () => {
    isWindows = navigator.platform.startsWith('Win') || /Windows/.test(navigator.userAgent);
    if (!isWindows) return;

    const win = getCurrentWindow();
    isMaximized = await win.isMaximized();
    unlistenResize = await win.onResized(async () => {
      isMaximized = await win.isMaximized();
    });
  });

  onDestroy(() => {
    unlistenResize?.();
  });

  async function minimize() {
    await getCurrentWindow().minimize();
  }

  async function toggleMaximize() {
    const win = getCurrentWindow();
    if (isMaximized) {
      await win.unmaximize();
    } else {
      await win.maximize();
    }
  }

  async function close() {
    await getCurrentWindow().close();
  }
</script>

{#if isWindows}
  <div
    class="-mr-1 flex h-full items-center"
    role="toolbar"
    aria-label="Window controls"
    aria-orientation="horizontal"
  >
    <button
      onclick={minimize}
      class="flex h-full w-11 items-center justify-center text-[var(--sg-text-dim)] hover:bg-[var(--sg-surface-raised)] hover:text-[var(--sg-text)]"
      title="Minimize"
      aria-label="Minimize"
      data-tauri-drag-region-exclude
    >
      <Minus size={14} />
    </button>
    <button
      onclick={toggleMaximize}
      class="flex h-full w-11 items-center justify-center text-[var(--sg-text-dim)] hover:bg-[var(--sg-surface-raised)] hover:text-[var(--sg-text)]"
      title={isMaximized ? 'Restore' : 'Maximize'}
      aria-label={isMaximized ? 'Restore' : 'Maximize'}
      data-tauri-drag-region-exclude
    >
      {#if isMaximized}
        <Minimize2 size={14} />
      {:else}
        <Square size={14} />
      {/if}
    </button>
    <button
      onclick={close}
      class="close-btn flex h-full w-11 items-center justify-center text-[var(--sg-text-dim)] hover:text-white"
      title="Close"
      aria-label="Close"
      data-tauri-drag-region-exclude
    >
      <X size={14} />
    </button>
  </div>
{/if}

<style>
  .close-btn:hover {
    background-color: var(--sg-danger);
  }
</style>
